server.port=8081
server.ssl.enabled=false

spring.datasource.url=jdbc:h2:file:./data/asistencia-dev;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.show-sql=true
